apiVersion: v1
kind: Namespace
metadata:
  name: indichess
  labels:
    name: indichess
---
apiVersion: v1
kind: Namespace
metadata:
  name: indichess-monitoring
  labels:
    name: indichess-monitoring
