apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: indichess
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DRIVER: org.postgresql.Driver
  HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: indichess
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-config
  namespace: indichess
data:
  JWT_EXPIRATION: "86400000"
  JWT_REFRESH_EXPIRATION: "604800000"
