apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: indichess
type: Opaque
stringData:
  DB_USER: indichess_user
  DB_PASSWORD: changeme123!secure
  POSTGRES_PASSWORD: postgres123!secure
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: indichess
type: Opaque
stringData:
  JWT_SECRET: mySecretKeyForJWTTokenGenerationAndValidationPurposeThatIsLongEnough
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: indichess
type: docker.io/docker-registry
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJ5b3VydXNlcm5hbWUiLCJwYXNzd29yZCI6InlvdXJwYXNzd29yZCIsImF1dGgiOiJkbTlrWVhRdWJHOW5ZV3dFYUc5a1lRPT0ifX19
imagePullSecrets:
- name: docker-registry
